name: Rickpedia CI
on:
  push:
    branches:
      - main
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Criar variáveis de ambiente
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: echo "BASE_URL=${{env.BASE_URL}}" > .env

  build:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install npm dependencies
        run: yarn install
      - name: Run build task
        run: npx vite build
      - name: Deploy para meu hosting
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/ config/ src/image"
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{secrets.REMOTE_TARGET}}
